### ISSUE TITLE
Portable .snap fails to run with a JavaScript error

### ISSUE THREAD

**Issue by zhuher** [gorilla-devs/GDLauncher#1044]
**Describe the bug**
What happens when I try to launch GDLauncher portable .snap on Pop!_OS via terminal:
user@pc:~$ gdlauncher
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /snap/gdlauncher/x1/resources/app.asar/build/native/linux/nsfw.node: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /run/user/1000/snap.gdlauncher/.org.chromium.Chromium.cWN3Xf)
    at Object.eval (webpack-internal:///./public/native/linux/nsfw.node:1:233)
    at eval (webpack-internal:///./public/native/linux/nsfw.node:2:30)
    at Object../public/native/linux/nsfw.node (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:2262570)
    at e (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/native/nsfw.js:15:10)
    at Object../public/native/nsfw.js (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:2265836)
    at e (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/electron.js:49:14)
    at Object../public/electron.js (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:2213146)
    at e (/snap/gdlauncher/x1/resources/app.asar/build/electron.js:1:124)
Gtk-Message: 17:21:54.349: Failed to load module "appmenu-gtk-module"

**To Reproduce**
1. Be me, living in a society
2. Install snap
3. Install --dangerous gdlauncher*.snap
4. Try to launch via terminal
5. See error

**Expected behavior**
GDLauncher launches like normal.

**Possible solutions**
Idk I'd love to hear some

**Screenshots**
No.

**Operating System:**
 - OS: Pop!_OS
 - Version: 21.04

**Additional context**
No.

**Comment by huantianad** [comment]
Seems like a glibc version incompatibility, might take some more looking into.
For now, maybe try installing via the deb package.

**Comment by ghost** [comment]
The snap is out of date (using `0.10.3-beta`) and should not be used.  

If you are using a `.snap` file then you should check to see if your dependencies are up to date, like `glibc`. 

Also, personally, I think that snap is bad and shouldn't be used.

**Comment by huantianad** [comment]
I also do agree that snap is bad and shouldn't be used, but this is probably not the place to discuss this lmao.
You can probably find the updated snap in the releases page

**Comment by zhuher** [comment]
> You can probably find the updated snap in the releases page

Ye, that was the latest release snap at the time of me posting the initial issue...

**Comment by Corosauce** [comment]
Same issue here with the GDLauncher-linux-setup.AppImage I just tried on their site, .deb file too.

I managed to fix it for my KDE Neon setup based on ubuntu 18.04, despite my system seeming to have GLIBCXX_3.4.26, I had to install libstdc++6 as well as some other things, the comamnds I ended up running:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9
sudo apt install libstdc++6
```

Sources: 
https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04
https://askubuntu.com/questions/1166292/version-glibcxx-3-4-26-not-found-even-though-libstdc-so-6-recent-enough
