### ISSUE TITLE
App threw an error during load

### ISSUE THREAD

**Issue by The-Corrupted** [gorilla-devs/GDLauncher#1071]
**Describe the bug**
An error occurs in the main process for gdlauncher-1.1.15 when trying to launch the application

**To Reproduce**
* Use rua to install gdlauncher-beta ( rua install gdlauncher-beta )
* Attempt to launch gdlauncher

**Expected behavior**
The application launches successfully

**Operating System:**
- OS: Arch
- Version: 5.14.2-zen
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
This may be related to #1069. The beta (1.1.15) fails to launch with the following error:

```
App threw an error during load
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1)
    at Object.writeFileSync (fs.js:1517:5)
    at eval (webpack-internal:///./public/electron.js:176:7)
    at Object../public/electron.js (/usr/lib/gdlauncher/build/electron.js:1:653453)
    at e (/usr/lib/gdlauncher/build/electron.js:1:124)
    at module.exports../node_modules/base64url/dist/base64url.js (/usr/lib/gdlauncher/build/electron.js:1:923)
    at Object.<anonymous> (/usr/lib/gdlauncher/build/electron.js:1:953)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)

```

On the stable build ( 1.1.14 ) the application launches but gets stuck in the load screen. Checking the developer tools nets the same error as found on 1.1.15:

```
App threw an error during load
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1)
    at Object.writeFileSync (fs.js:1517:5)
    at eval (webpack-internal:///./public/electron.js:176:7)
    at Object../public/electron.js (/usr/lib/gdlauncher/build/electron.js:1:653453)
    at e (/usr/lib/gdlauncher/build/electron.js:1:124)
    at module.exports../node_modules/base64url/dist/base64url.js (/usr/lib/gdlauncher/build/electron.js:1:923)
    at Object.<anonymous> (/usr/lib/gdlauncher/build/electron.js:1:953)
    at Module._compile (internal/modules/cjs/loader.js:1083:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1113:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Module._load (internal/modules/cjs/loader.js:781:14)
```

**Comment by SaltSouls** [comment]
I can confirm that I'm getting the same error when launching on Manjaro 5.14.2.1.

**Comment by Eskaan** [comment]
Is your PC ARM64-based?

**Comment by SaltSouls** [comment]
> Is your PC ARM64-based?

No, mine is x86_64
My specs are as follows:
CPU: AMD Ryzen 7 3800X (16) @ 4.200GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
Memory: 32Gb DDR4 3200mhz.
And I'm using Plasma 5.22.5 for my environment.

**Comment by Eskaan** [comment]
Thanks. Sadly I have no Idea what could have caused the errors to pop up.

**Comment by huantianad** [comment]
Does this also happen with the `gdlauncher-beta-bin` package?

**Comment by The-Corrupted** [comment]
> Does this also happen with the `gdlauncher-beta-bin` package?

No it does not. This appears to be an issue with the aur package. Building from source and using that or using the bin packages works fine

**Comment by huantianad** [comment]
@The-Corrupted can you check what electron version you have currently? `pacman -Qs electron`

**Comment by The-Corrupted** [comment]
@huantianad I appear to have two electron versions currently. electron - 15.1.0-1 and electron11 - 11.5.0-2.

**Comment by huantianad** [comment]
That should be fine, can you try `cd`ing to `/usr/lib/gdlauncher/` and running `electron .`?

**Comment by The-Corrupted** [comment]
Sure, gdlauncher launches as expected if I cd into the gdlaucher dir and run electron. It also launches as expected when launching it via /bin/gdlauncher. The same is true for gdlauncher-beta.

**Comment by huantianad** [comment]
@The-Corrupted Interesting, it may have been fixed in the latest beta update, or perhaps in the electron update.

Or, it could've been some other system package upgrade/configuration change?

**Comment by The-Corrupted** [comment]
@huantianad Perhaps, though I should note that it is still possible to trigger this error by trying to launch it as such:
`electron /usr/lib/gdlauncher/`
I rolled back my electron version to the previous 15 release ( 15.0.0-1 worked ) and tried out a couple of the 14 releases as well ( worked up until 14.0.0-1 ) so I'm not sure it was an electron issue.

**Comment by huantianad** [comment]
@The-Corrupted oh interesting, I did actually change the launch script for the beta version to first cd to the folder, then run the electron command instead of doing it all in one go, to fix a possibly related bug.

This might be due to some weird relative path in the code somewhere, so you have to launch it from the installation directory.
