### ISSUE TITLE
Duplicate ASM on Fabric 1.21.3

### ISSUE THREAD

**Issue by Od1n2018** [gorilla-devs/GDLauncher#1620]
- [ X] I searched the issue tracker for other issues covering my case
- [X ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
On attempts to create and launch a 1.21.3 instance in fabric on fabric loader 0.16 and above the instance does an automatic crash. The error logs state that there is a duplicate ASM. I deleted GDlauncher and all folder associated with it first to see if it was my GDLauncher out of date. Same crash happened. Also deleted the duplicating ASM folders. Both just redownload and give same error. 

**To Reproduce**
1. Create Instance of 1.21.3 on Fabric loader above 0.16
2. Attempt to load.

**Expected behavior**
I expected it to launch a 1.21.3 instance

**Possible solutions**
No idea how to solve this issue

**Logs**
GDLauncher@N/A: Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: jar:file:/C:/Users/""Username"/AppData/Roaming/gdlauncher_carbon/data/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar!/org/objectweb/asm/ClassReader.class, jar:file:/C:/Users/"Username"/AppData/Roaming/gdlauncher_carbon/data/libraries/org/ow2/asm/asm/9.7.1/asm-9.7.1.jar!/org/objectweb/asm/ClassReader.class
	at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:83)
	at net.fabricmc.loader.impl.launch.knot.Knot.

**Operating System:**
- OS: Windows 11
- Launcher Version: 2.0.20
- Java Version: 21
- Minecraft Version:1.21.3
- Mod Loader: Fabric

**Additional context**
_Add any other context about the problem here._

**Comment by Benjamin-Wirz** [comment]
I am also having the same issue, However I can get it to launch on Fabric Loader 0.16.1. I have the exact same system info/settings listed, except I am running Manjaro Linux, which now doesn't seem to be a factor. I also found out that Neoforge exits with the same exit code however Forge still works. Hope this info helps

**Comment by desaianand1** [comment]
This is the legacy repository for GDLauncher. All future issues will be handled on the new Carbon repository, [here](https://github.com/gorilla-devs/GDLauncher-Carbon/issues/)

This issue is already tracked there: [#383](https://github.com/gorilla-devs/GDLauncher-Carbon/issues/383)
It is seemingly patched already and will go live on the next release candidate

**Comment by the-r3dacted** [comment]
I made a fixed version of fabric that doesn't have this bug.
https://github.com/K4sum1/fabric-loader-fixed/releases/tag/0.16.10-fixed
