### ISSUE TITLE
Right after `yarn package-all`

### ISSUE THREAD

**Issue by MtechnikX** [gorilla-devs/GDLauncher#181]
**E:\WestgateXL>yarn package-all**
_yarn run v1.15.2_
```
$ yarn build && cross-env ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true electron-builder build -mwl
$ yarn build-antd && concurrently "yarn build-main" "yarn build-renderer"
$ lessc --js ./antd/index.less ./app/antd.css
$ cross-env NODE_ENV=production webpack --config ./config/webpack.config.main.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./config/webpack.config.renderer.prod.babel.js --colors
[0] Hash: 0de8409ee4e6d7b1d935
[0] Version: webpack 4.29.6
[0] Time: 18755ms
[0] Built at: 04/09/2019 7:02:06 PM
[0]                  Asset      Size  Chunks             Chunk Names
[0]     ./app/main.prod.js   902 KiB       0  [emitted]  main
[0] ./app/main.prod.js.map  3.66 MiB       0  [emitted]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.js] ./app/main.dev.js + 29 modules 81.6 KiB {0} [built]
[0]     | ./app/main.dev.js 6.75 KiB [built]
[0]     | ./app/localStore.js 63 bytes [built]
[0]     | ./app/constants.js 3.64 KiB [built]
[0]     | ./app/menu.js 6.14 KiB [built]
[0]     | ./app/utils/cli.js 807 bytes [built]
[0]     | ./app/utils/getAppPath.js 191 bytes [built]
[0]     | ./app/utils/MCLaunchCommand.js 3.9 KiB [built]
[0]     | ./app/utils/javaHelpers.js 1.33 KiB [built]
[0]     | ./app/utils/getMCFilesList.js 5.18 KiB [built]
[0]     | ./app/utils/strings.js 1.22 KiB [built]
[0]     |     + 20 hidden modules
[0] [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [http] external "http" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [timers] external "timers" 42 bytes {0} [built]
[0] [url] external "url" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 1488 hidden modules
[0]
[0] WARNING in ./node_modules/ws/lib/buffer-util.js
[0] Module not found: Error: Can't resolve 'bufferutil' in 'E:\WestgateXL\node_modules\ws\lib'
[0]  @ ./node_modules/ws/lib/buffer-util.js
[0]  @ ./node_modules/ws/lib/sender.js
[0]  @ ./node_modules/ws/index.js
[0]  @ ./node_modules/discord-rpc/src/transports/WebSocket.js
[0]  @ ./node_modules/discord-rpc/src/transports/index.js
[0]  @ ./node_modules/discord-rpc/src/Client.js
[0]  @ ./node_modules/discord-rpc/src/index.js
[0]  @ ./app/main.dev.js
[0]
[0] WARNING in ./node_modules/discord-rpc/src/Util.js
[0] Module not found: Error: Can't resolve 'register-scheme' in 'E:\WestgateXL\node_modules\discord-rpc\src'
[0]  @ ./node_modules/discord-rpc/src/Util.js
[0]  @ ./node_modules/discord-rpc/src/index.js
[0]  @ ./app/main.dev.js
[0]
[0] WARNING in ./node_modules/ws/lib/validation.js
[0] Module not found: Error: Can't resolve 'utf-8-validate' in 'E:\WestgateXL\node_modules\ws\lib'
[0]  @ ./node_modules/ws/lib/validation.js
[0]  @ ./node_modules/ws/lib/sender.js
[0]  @ ./node_modules/ws/index.js
[0]  @ ./node_modules/discord-rpc/src/transports/WebSocket.js
[0]  @ ./node_modules/discord-rpc/src/transports/index.js
[0]  @ ./node_modules/discord-rpc/src/Client.js
[0]  @ ./node_modules/discord-rpc/src/index.js
[0]  @ ./app/main.dev.js
[0] yarn build-main exited with code 0
[1] Hash: 5771cc1a5019d4b3df5f
[1] Version: webpack 4.29.6
[1] Time: 41020ms
[1] Built at: 04/09/2019 7:02:29 PM
[1]                                Asset       Size  Chunks             Chunk Names
[1]                                10.js   3.95 KiB      10  [emitted]
[1]                            10.js.map   9.54 KiB      10  [emitted]
[1]                         10.style.css  279 bytes      10  [emitted]
[1]                                11.js   3.74 KiB      11  [emitted]
[1]                            11.js.map   6.98 KiB      11  [emitted]
[1]                         11.style.css  957 bytes      11  [emitted]
[1]                                12.js   2.28 KiB      12  [emitted]
[1]                            12.js.map   2.91 KiB      12  [emitted]
[1]                         12.style.css   75 bytes      12  [emitted]
[1]                                13.js   4.68 KiB      13  [emitted]
[1]                            13.js.map   12.3 KiB      13  [emitted]
[1]                         13.style.css  522 bytes      13  [emitted]
[1] 13dc531a2ffd9ca7eeb500515774fa74.otf   53.5 KiB          [emitted]
[1]                                 2.js   6.19 KiB       2  [emitted]
[1]                             2.js.map   13.7 KiB       2  [emitted]
[1]                          2.style.css   4.61 KiB       2  [emitted]
[1]                                 3.js   2.01 KiB       3  [emitted]
[1]                             3.js.map    2.9 KiB       3  [emitted]
[1]                          3.style.css  279 bytes       3  [emitted]
[1]                                 4.js   3.89 KiB       4  [emitted]
[1]                             4.js.map   6.26 KiB       4  [emitted]
[1]                          4.style.css   2.06 KiB       4  [emitted]
[1] 4eaf1f3f8d608a83205e4fb73550e5eb.wav   7.04 KiB          [emitted]
[1]                                 5.js    2.1 KiB       5  [emitted]
[1]                             5.js.map   3.59 KiB       5  [emitted]
[1]                          5.style.css  475 bytes       5  [emitted]
[1]                                 6.js   3.21 KiB       6  [emitted]
[1]                             6.js.map   7.21 KiB       6  [emitted]
[1]                          6.style.css  876 bytes       6  [emitted]
[1]                                 7.js   3.47 KiB       7  [emitted]
[1]                             7.js.map   8.28 KiB       7  [emitted]
[1]                          7.style.css  312 bytes       7  [emitted]
[1]                                 8.js   7.81 KiB       8  [emitted]
[1]                             8.js.map   17.7 KiB       8  [emitted]
[1]                          8.style.css  482 bytes       8  [emitted]
[1]                                 9.js   3.23 KiB       9  [emitted]
[1]                             9.js.map   7.46 KiB       9  [emitted]
[1]                          9.style.css  249 bytes       9  [emitted]
[1] 922d8d408382cfc5aba6abf4f4e58233.otf   36.1 KiB          [emitted]
[1] a1424d62ea0f8b960139263c364a0f10.otf   32.2 KiB          [emitted]
[1] f801e234d51049bd538d3d95f6f4e110.otf   30.3 KiB          [emitted]
[1]                     renderer.prod.js    806 KiB       1  [emitted]  main
[1]                 renderer.prod.js.map   1.02 MiB       1  [emitted]  main
[1]                            style.css    449 KiB       1  [emitted]  main
[1]                            vendor.js   2.93 MiB       0  [emitted]  vendor
[1]                        vendor.js.map   9.42 MiB       0  [emitted]  vendor
[1] Entrypoint main = vendor.js vendor.js.map style.css renderer.prod.js renderer.prod.js.map
[1] [./app/actions/auth.js] 7.98 KiB {1} [built]
[1] [./app/actions/downloadManager.js] ./app/actions/downloadManager.js + 1 modules 12.4 KiB {1} [built]
[1]     | ./app/actions/downloadManager.js 11.3 KiB [built]
[1]     | ./app/utils/assets.js 1.02 KiB [built]
[1] [./app/actions/settings.js] 4 KiB {1} [built]
[1] [./app/app.global.scss] 229 bytes {1} [built]
[1] [./app/assets/images/creeper.png] 15.7 KiB {1} [built]
[1] [./app/components/ChangelogModal/ChangelogModal.js] ./app/components/ChangelogModal/ChangelogModal.js + 1 modules 5.23 KiB {4} [built]
[1]     |    2 modules
[1] [./app/components/CurseModpackExplorerModal/CurseModpackExplorerModal.js] ./app/components/CurseModpackExplorerModal/CurseModpackExplorerModal.js + 1 modules 4.35 KiB {6} [built]
[1]     | ./app/hooks/cursemeta.js 327 bytes [built]
[1]     |     + 1 hidden module
[1] [./app/components/ExportPackModal/ExportPackModal.js] ./app/components/ExportPackModal/ExportPackModal.js + 5 modules 15.4 KiB {8} [built]
[1]     |    6 modules
[1] [./app/components/Home/containers/HomePage.js] ./app/components/Home/containers/HomePage.js + 2 modules 8.54 KiB {2} [built]
[1]     |    3 modules
[1] [./app/components/InstanceCreatorModal/containers/InstanceCreatorModal.js] ./app/components/InstanceCreatorModal/containers/InstanceCreatorModal.js + 1
modules 5.94 KiB {10} [built]
[1]     |    2 modules
[1] [./app/components/Login/Login.js] ./app/components/Login/Login.js + 1 modules 6.9 KiB {13} [built]
[1]     | ./app/utils/nativeLauncher.js 776 bytes [built]
[1]     |     + 1 hidden module
[1] [./app/constants.js] ./app/constants.js + 1 modules 3.84 KiB {1} [built]
[1]     | ./app/constants.js 3.64 KiB [built]
[1]     | ./app/utils/getAppPath.js 191 bytes [built]
[1] [./app/index.js] ./app/index.js + 72 modules 206 KiB {1} [built]
[1]     | ./app/index.js 1.85 KiB [built]
[1]     | ./app/store/configureStore.js 333 bytes [built]
[1]     | ./app/containers/Root.js 1.97 KiB [built]
[1]     | ./app/store/configureStore.dev.js 2.2 KiB [built]
[1]     | ./app/store/configureStore.prod.js 562 bytes [built]
[1]     | ./app/routes.js 9.43 KiB [built]
[1]     | ./app/GAnalytics.js 105 bytes [built]
[1]     | ./app/containers/App.js 1.41 KiB [built]
[1]     | ./app/utils/javaHelpers.js 1.33 KiB [built]
[1]     | ./app/reducers/index.js 535 bytes [built]
[1]     | ./app/containers/Navigation.js 481 bytes [built]
[1]     | ./app/actions/profile.js 496 bytes [built]
[1]     | ./app/reducers/profile.js 654 bytes [built]
[1]     | ./app/reducers/auth.js 1.93 KiB [built]
[1]     | ./app/reducers/packCreator.js 759 bytes [built]
[1]     |     + 58 hidden modules
[1] [./node_modules/connected-react-router/esm/index.js] ./node_modules/connected-react-router/esm/index.js + 6 modules 17 KiB {0} [built]
[1]     |    7 modules
[1] [./node_modules/react-redux/es/index.js] ./node_modules/react-redux/es/index.js + 14 modules 28.7 KiB {0} [built]
[1]     |    15 modules
[1]     + 1824 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/sass-loader/lib/loader.js??ref--7-2!app/app.global.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./app/assets/fonts/GlacialIndifferenceBold.otf] 82 bytes {0} [built]
[1]     [./app/assets/fonts/GlacialIndifferenceItalic.otf] 82 bytes {0} [built]
[1]     [./app/assets/fonts/GlacialIndifferenceMedium.otf] 82 bytes {0} [built]
[1]     [./app/assets/fonts/GlacialIndifferenceRegular.otf] 82 bytes {0} [built]
[1]     [./node_modules/css-loader/dist/cjs.js?!./node_modules/sass-loader/lib/loader.js?!./app/antd.css] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/sass-loader/lib/loader.js??ref--7-2!./app/antd.css 1.21 MiB {0} [built]
[1]     [./node_modules/css-loader/dist/cjs.js?!./node_modules/sass-loader/lib/loader.js?!./app/app.global.scss] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/sass-loader/lib/loader.js??ref--7-2!./app/app.global.scss 44.2 KiB {0} [built]
[1]         + 2 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/AutoUpdate/AutoUpdate.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/ChangelogModal/ChangelogModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/Badge/Badge.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/Card/Card.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/CopyIcon/CopyIcon.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/Icon/Icon.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/Modal/Modal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SideBar/SideBar.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SideBar/SocialIcon.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SideMenu/MenuItem/MenuItem.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SideMenu/SideMenu.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SystemNavBar/SystemNavBar.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SystemNavBar/components/OpenDevTools/OpenDevTools.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SystemNavBar/components/WindowCloseButton/WindowCloseButton.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SystemNavBar/components/WindowHideButton/WindowHideButton.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/SystemNavBar/components/WindowMinimizeButton/WindowMinimizeButton.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/WindowNavigation/NavigationBar.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Common/WindowNavigation/components/HorizontalMenu/HorizontalMenu.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/ConfirmDeleteModal/ConfirmDeleteModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/CrashHandler/CrashHandler.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/CurseModpackExplorerModal/CurseModpackExplorerModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/CurseModpacksBrowserCreatorModal/CurseModpackBrowserCreatorModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/CurseModpacksBrowser/CurseModpacksBrowser.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/DInstance/DInstance.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/DManager/DManager.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./app/assets/images/dmanagerBG.jpg] 120 KiB {0} [built]
[1]         + 3 hidden modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/ExportPackModal/ExportPackModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Home/Home.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Home/components/News/News.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/ImportPack/ImportPack.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceCreatorModal/InstanceCreatorModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/InstanceManagerModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/ModsManager/LocalMods/LocalMods.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/ModsManager/ModsBrowser/ModPage.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/ModsManager/ModsBrowser/ModsList.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/ModsManager/ModsBrowser/ModsListHeader.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/ModsManager/ModsManager.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/Settings/ForgeManager.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/Settings/JavaManagerCard.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/InstanceManagerModal/Settings/Settings.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/JavaGlobalOptionsFixModal/JavaGlobalOptionsFixModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/LoginHelperModal/LoginHelperModal.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Login/Login.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/Settings.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/ButtonSetting/ButtonSetting.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/Content/Content.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/Instances/Instances.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/JavaManager/JavaManager.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/JavaManager/javaMemorySlider.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/MyAccount_Preferences/MyAccount_Preferences.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/SelectSetting/SelectSetting.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/SettingCard/SettingCard.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/SettingInput/SettingInput.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/SwitchSetting/SwitchSetting.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/Title/Title.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/components/Settings/components/UserInterface/UserInterface.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]        2 modules
[1] Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--8-1!node_modules/sass-loader/lib/loader.js??ref--8-2!app/style/theme/colors.scss:
[1]     Entrypoint mini-css-extract-plugin = *
[1]     [./node_modules/css-loader/dist/cjs.js?!./node_modules/sass-loader/lib/loader.js?!./app/style/theme/colors.scss] ./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/sass-loader/lib/loader.js??ref--8-2!./app/style/theme/colors.scss 4.23 KiB {0} [built]
[1]         + 1 hidden module
[1] yarn build-renderer exited with code 0
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
Error: Invalid version: "2.0.0.0"
    at Object.fixVersionField (E:\WestgateXL\node_modules\normalize-package-data\lib\fixer.js:191:13)
    at E:\WestgateXL\node_modules\normalize-package-data\lib\normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (E:\WestgateXL\node_modules\normalize-package-data\lib\normalize.js:31:15)
    at E:\WestgateXL\node_modules\app-builder-lib\src\util\packageMetadata.ts:13:3
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at _readPackageJson (E:\WestgateXL\node_modules\app-builder-lib\out\util\packageMetadata.js:71:27)
    at readPackageJson (E:\WestgateXL\node_modules\app-builder-lib\out\util\packageMetadata.js:58:27)
    at E:\WestgateXL\node_modules\app-builder-lib\src\packager.ts:304:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (E:\WestgateXL\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (E:\WestgateXL\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (E:\WestgateXL\node_modules\electron-builder\src\builder.ts:228:10)
    at then (E:\WestgateXL\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Ladvace** [comment]
Have you done "yarn" first?

**Comment by blarfoon** [comment]
Unless you're using a mac, `yarn package-all` will always fail. Mac builds can only be built on mac. Use `yarn package` or `yarn package-win` / `yarn package-linux` instead
