### ISSUE TITLE
Can't Start Instances

### ISSUE THREAD

**Issue by bluewarbler** [gorilla-devs/GDLauncher#204]
When I attempt to start up an instance of any modpack, regardless of what that modpack is, it automatically fails to launch.  Opening the log reveals the following error log:

exception in thread "main"
java.lang.UnsupportedClassVersionError: joptsimple/OptionSpec : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

OS: macOS Mojave version 10.14.4

I have installed all the necessary Java files that I know of (latest edition of Java, the necessary JDK).  Regular Minecraft, even with mods, works fine.

**Comment by blarfoon** [comment]
We have some issues with macOS. We will try to fix this

**Comment by TOLoneWolf** [comment]
Java 8 is required for most minecraft versions. You will need to make sure to use that.  
version 0.12.4 of GDL should fix all the other problems for osx launching minecraft, simply reinstall any packs that do not launch correctly should fix them. If not please make a new issue about them with logs.  
https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files  

Closing as this should be resolved.
