### ISSUE TITLE
I cant open the settings 

### ISSUE THREAD

**Issue by Te-but** [gorilla-devs/GDLauncher#302]
When I try to open settings gdlaucher has crash and i see this in console 

> TypeError: Cannot read property 'charAt' of undefined
    at MyAccount_Preferences.js:35
    at Ri (react-dom.production.min.js:148)
    at Zs (react-dom.production.min.js:245)
    at Bs (react-dom.production.min.js:216)
    at Vs (react-dom.production.min.js:210)
    at Ds (react-dom.production.min.js:206)
    at react-dom.production.min.js:114
    at t.unstable_runWithPriority (scheduler.production.min.js:20)
    at fo (react-dom.production.min.js:113)
    at yo (react-dom.production.min.js:114)
    at vo (react-dom.production.min.js:113)
    at Is (react-dom.production.min.js:207)
    at Hn (react-dom.production.min.js:86)
Da @ react-dom.production.min.js:187
Ka.i.componentDidCatch.n.callback @ react-dom.production.min.js:201
Vo @ react-dom.production.min.js:125
Ro @ react-dom.production.min.js:125
Ws @ react-dom.production.min.js:238
t.unstable_runWithPriority @ scheduler.production.min.js:20
fo @ react-dom.production.min.js:113
qs @ react-dom.production.min.js:230
Ds @ react-dom.production.min.js:206
(anonymous) @ react-dom.production.min.js:114
t.unstable_runWithPriority @ scheduler.production.min.js:20
fo @ react-dom.production.min.js:113
yo @ react-dom.production.min.js:114
vo @ react-dom.production.min.js:113
Is @ react-dom.production.min.js:207
Hn @ react-dom.production.min.js:86
console.js:72 12:24:02.320 › TypeError: Cannot read property 'charAt' of undefined
    at file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/renderer.prod.js:1:324200
    at Ri (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:55449)
    at Zs (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:98380)
    at Bs (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:84006)
    at Vs (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:81033)
    at Ds (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:79606)
    at file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:41871
    at t.unstable_runWithPriority (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:278:3878)
    at fo (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:41600)
    at yo (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:41817)
    at vo (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:41752)
    at Is (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:80033)
    at Hn (file:///C:/Users/Pececik/AppData/Local/Programs/gdlauncher/resources/app.asar/app/dist/vendor.js:74:31413) { componentStack:
   '\n    in Unknown\n    in f\n    in t\n    in div\n    in div\n    in Er\n    in div\n    in div\n    in div\n    in div\n    in d\n    in xr\n    in t\n    in ye\n    in w\n    in f\n    in t\n    in n\n    in i\n    in f\n    in div\n    in f\n    in Ti\n    in i' }

**Comment by TOLoneWolf** [comment]
Try This out and let me know if that lets you into your settings.
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#crash-when-opening-settings

**Comment by Te-but** [comment]
Thank you it working ,but I use 0.12.4 version not 0.14.3.
