### ISSUE TITLE
[Feature Request] Add MultiMC Import Option

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#592]
**Describe the bug**

**To Reproduce**
1. Import `.zip` exported from multimc.

**Expected behavior**
I expected to be able to import my modpack from multimc into gd, but obviously it didn't work, it just loads forever. The .zip file is named `aether.zip`, yet I get `Instance name is not vaild...` every time I try running gd. Here's the log: 
```18:08:32.076 › setup
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
18:08:33.671 › Trying to start listener
18:08:33.673 › Started listener
18:08:34.716 › Unable to initialize Discord RPC: Error: Could not connect
    at Socket.onerror (webpack-internal:///./node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Checking for update
Update for version 1.0.8 is not available (latest version: 1.0.8, downgrade is disallowed).
```

**Possible solutions**
1) I think the path might be included in the name for some reason as a possible explanation to why the name is invalid no matter what I name it or where I place it.

**Operating System:**
 - OS: Fedora Linux 32
 - Version: Most recent appimage.

**Additional Information**
I'm totally able to install modpacks from the browser. I'm certain this is just an issue with local files on *nix systems.

**Comment by ghost** [comment]
This is unrelated to this issue, but in the categories, the rest of RPG is cut out. Just an aesthetic issue that I didn't feel like was worth making a new issue over.

**Comment by TOLoneWolf** [comment]
gdl does not have a mmc import option only twitch format works.

**Comment by TayouVR** [comment]
is this gonna be worked on eventually, or can I maybe help with it?
Today I found this and manually transferred most of my MultiMC instances over here. Being able to properly import them... or even find them automatically and mass import would be very helpful.

If there are no resources free to work on this, I could maybe give it a go myself, I would need a hint though, where to start. Which file(s), which function(s), etc.

**Comment by Eskaan** [comment]
If you are a developer, we would love to see MultiMC import support in our Pull Requests ❤️
Otherwise it will take its time untill one of our Contributors does it 🙂 

> is this gonna be worked on eventually, or can I maybe help with it?
> Today I found this and manually transferred most of my MultiMC instances over here. Being able to properly import them... or even find them automatically and mass import would be very helpful.
> 
> If there are no resources free to work on this, I could maybe give it a go myself, I would need a hint though, where to start. Which file(s), which function(s), etc.

**Comment by kreezxil** [comment]
What do we need to make MultiMC zip importing a reality? If more $$ let me know, I might be able to help there.
