### ISSUE TITLE
[doc] python2 requirement for compiling not specified on README

### ISSUE THREAD

**Issue by rmobis** [gorilla-devs/GDLauncher#719]
**Describe the bug**
Not really a bug on the software, but on the documentation. The README.md states that only Node, Rust and a C++ compiler are required to compile, but if you don't have `python2` installed, you get the following error when building `neon-sys` during the `npm install` process.

```      /d/projects/GDLauncher     master ······································ 18s    15.4.0    22:16:46 
❯ npm i
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /home/rmobis/.nvm/versions/node/v15.4.0/bin/node /home/rmobis/.nvm/versions/node/v15.4.0/lib/node_modules/npm/bin/npm-cli.js install --cache=/home/rmobis/.npm/_cacache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! > murmur2-calculator@0.1.0 install
npm ERR! > neon build --release
npm ERR!
npm ERR! neon info forcing rebuild for new build settings
npm ERR! neon info running cargo
npm ERR! Updating git repository `https://github.com/gorilla-devs/murmurhash32.git`
npm ERR!  Downloading crates ...
npm ERR!   Downloaded num-traits v0.2.11
npm ERR!   Downloaded semver-parser v0.7.0
npm ERR!   Downloaded cc v1.0.50
npm ERR!   Downloaded aho-corasick v0.7.10
npm ERR!   Downloaded semver v0.9.0
npm ERR!   Downloaded autocfg v1.0.0
npm ERR!   Downloaded regex-syntax v0.6.17
npm ERR!   Downloaded num-integer v0.1.42
npm ERR!   Downloaded num-bigint v0.2.6
npm ERR!   Downloaded neon-build v0.3.3
npm ERR!   Downloaded cslice v0.2.0
npm ERR!   Downloaded neon-runtime v0.3.3
npm ERR!   Downloaded neon-sys v0.3.3
npm ERR!   Downloaded regex v1.3.5
npm ERR!   Downloaded neon v0.3.3
npm ERR!    Compiling memchr v2.3.3
npm ERR!    Compiling lazy_static v1.4.0
npm ERR!    Compiling regex-syntax v0.6.17
npm ERR!    Compiling cc v1.0.50
npm ERR!    Compiling autocfg v1.0.0
npm ERR!    Compiling cfg-if v0.1.10
npm ERR!    Compiling byteorder v1.3.4
npm ERR!    Compiling semver-parser v0.7.0
npm ERR!    Compiling cslice v0.2.0
npm ERR!    Compiling neon-build v0.3.3
npm ERR!    Compiling thread_local v1.0.1
npm ERR!    Compiling semver v0.9.0
npm ERR!    Compiling num-traits v0.2.11
npm ERR!    Compiling num-integer v0.1.42
npm ERR!    Compiling num-bigint v0.2.6
npm ERR!    Compiling aho-corasick v0.7.10
npm ERR!    Compiling murmurhash32 v0.2.0 (https://github.com/gorilla-devs/murmurhash32.git#40164089)
npm ERR!    Compiling regex v1.3.5
npm ERR!    Compiling neon-sys v0.3.3
npm ERR! error: failed to run custom build command for `neon-sys v0.3.3`
npm ERR!
npm ERR! Caused by:
npm ERR!   process didn't exit successfully: `/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-9cfab5d089c0ba51/build-script-build` (exit code: 101)
npm ERR!   --- stdout
npm ERR!
npm ERR!   > preinstall
npm ERR!   > echo 'Skipping node-gyp installation as part of npm install.'
npm ERR!
npm ERR!   Skipping node-gyp installation as part of npm install.
npm ERR!
npm ERR!   --- stderr
npm ERR!   thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
npm ERR!    Out:
npm ERR!   > configure-release
npm ERR!   > node-gyp configure --verbose
npm ERR!
npm ERR!
npm ERR!    Err: gyp info it worked if it ends with ok
npm ERR!   gyp verb cli [
npm ERR!   gyp verb cli   '/home/rmobis/.nvm/versions/node/v15.4.0/bin/node',
npm ERR!   gyp verb cli   '/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/.bin/node-gyp',
npm ERR!   gyp verb cli   'configure',
npm ERR!   gyp verb cli   '--verbose'
npm ERR!   gyp verb cli ]
npm ERR!   gyp info using node-gyp@3.6.2
npm ERR!   gyp info using node@15.4.0 | linux | x64
npm ERR!   gyp verb command configure []
npm ERR!   gyp verb check python checking for Python executable "python2" in the PATH
npm ERR!   gyp verb `which` failed Error: not found: python2
npm ERR!   gyp verb `which` failed     at getNotFoundError (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:13:12)
npm ERR!   gyp verb `which` failed     at F (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:68:19)
npm ERR!   gyp verb `which` failed     at E (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:80:29)
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:89:16
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/isexe/index.js:42:5
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/isexe/mode.js:8:5
npm ERR!   gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
npm ERR!   gyp verb `which` failed  python2 Error: not found: python2
npm ERR!   gyp verb `which` failed     at getNotFoundError (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:13:12)
npm ERR!   gyp verb `which` failed     at F (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:68:19)
npm ERR!   gyp verb `which` failed     at E (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:80:29)
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/which/which.js:89:16
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/isexe/index.js:42:5
npm ERR!   gyp verb `which` failed     at /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/isexe/mode.js:8:5
npm ERR!   gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
npm ERR!   gyp verb `which` failed   code: 'ENOENT'
npm ERR!   gyp verb `which` failed }
npm ERR!   gyp verb check python checking for Python executable "python" in the PATH
npm ERR!   gyp verb `which` succeeded python /usr/bin/python
npm ERR!   gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "3.8.5\n"
npm ERR!   gyp ERR! configure error
npm ERR!   gyp ERR! stack Error: Python executable "/usr/bin/python" is v3.8.5, which is not supported by gyp.
npm ERR!   gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
npm ERR!   gyp ERR! stack     at PythonFinder.failPythonVersion (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/node-gyp/lib/configure.js:492:19)
npm ERR!   gyp ERR! stack     at PythonFinder.<anonymous> (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/node-gyp/lib/configure.js:474:14)
npm ERR!   gyp ERR! stack     at ChildProcess.exithandler (node:child_process:324:7)
npm ERR!   gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR!   gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
npm ERR!   gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
npm ERR!   gyp ERR! System Linux 4.19.104-microsoft-standard
npm ERR!   gyp ERR! command "/home/rmobis/.nvm/versions/node/v15.4.0/bin/node" "/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native/node_modules/.bin/node-gyp" "configure" "--verbose"
npm ERR!   gyp ERR! cwd /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native
npm ERR!   gyp ERR! node -v v15.4.0
npm ERR!   gyp ERR! node-gyp -v v3.6.2
npm ERR!   gyp ERR! not ok
npm ERR!   npm ERR! code 1
npm ERR!   npm ERR! path /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/native/target/release/build/neon-sys-0a99d026cd93d4ab/out/native
npm ERR!   npm ERR! command failed
npm ERR!   npm ERR! command sh -c node-gyp configure --verbose
npm ERR!
npm ERR!   npm ERR! A complete log of this run can be found in:
npm ERR!   npm ERR!     /home/rmobis/.npm/_cacache/_logs/2020-12-17T01_18_31_527Z-debug.log
npm ERR!   ', /home/rmobis/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-sys-0.3.3/build.rs:148:9
npm ERR!   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
npm ERR! warning: build failed, waiting for other jobs to finish...
npm ERR! error: build failed
npm ERR! neon ERR! cargo build failed
npm ERR!
npm ERR! Error: cargo build failed
npm ERR!     at Target.<anonymous> (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/node_modules/neon-cli/lib/target.js:121:35)
npm ERR!     at step (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/node_modules/neon-cli/lib/target.js:32:23)
npm ERR!     at Object.next (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/node_modules/neon-cli/lib/target.js:13:53)
npm ERR!     at fulfilled (/home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f/node_modules/neon-cli/lib/target.js:4:58)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/rmobis/.npm/_cacache/tmp/git-clone-6da9f36f
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c neon build --release
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/rmobis/.npm/_cacache/_logs/2020-12-17T01_18_31_572Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rmobis/.npm/_logs/2020-12-17T01_21_02_204Z-debug.log
```

**To Reproduce**
While **not having python2 installed**, run:
1. `git clone https://github.com/gorilla-devs/GDLauncher.git`
2. `cd GDLauncher`
3. `npm i`

**Expected behavior**
I'd expect Python 2 listed as a compiling requirement on the README.

**Possible solutions**
List Python 2 as a compiling requirement on the README.

**Operating System:**
 - OS: Ubuntu (under WSL 2)
 - Version 20.04.1 LTS

**Comment by Ladvace** [comment]
I'm going to add it to the readme, btw I think this is needed just on mac and linux because on win it's already installed by one of the dependencies (I don't remember which one)
