### ISSUE TITLE
can't install beta git for 1.1.0 on manjaro

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#742]
```
> gdlauncher@1.1.0-beta.2 preinstall /var/tmp/pamac-build-kreezxil/gdlauncher-git/src/GDLauncher
> node ./scripts/preinstall.js

/var/tmp/pamac-build-kreezxil/gdlauncher-git/src/GDLauncher/scripts/preinstall.js:6
  throw new Error(`Please install node ${REQUIRED_NODE_VERSION} x64`);
  ^

Error: Please install node v14.14.0 x64
    at Object.<anonymous> (/var/tmp/pamac-build-kreezxil/gdlauncher-git/src/GDLauncher/scripts/preinstall.js:6:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gdlauncher@1.1.0-beta.2 preinstall: `node ./scripts/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdlauncher@1.1.0-beta.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/tmp/pamac-build-kreezxil/gdlauncher-git/src/npm-cache/_logs/2021-01-06T23_29_43_441Z-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
```
I install node 14 but apparently the exact version didn't match, so I tried node 15. it's insisting on the exact version. Should it not require a version and any subsequent versions?

**Comment by kreezxil** [comment]
found an article that allowed me to explicitly install that version
```bash
[kreezxil@32gRig ~]$ source /usr/share/nvm/init-nvm.sh 
[kreezxil@32gRig ~]$ nvm install 14.14.0
Downloading and installing node v14.14.0...
Downloading https://nodejs.org/dist/v14.14.0/node-v14.14.0-linux-x64.tar.xz...
#################################################################################################################################################### 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v14.14.0 (npm v6.14.8)
```
got the same error.

**Comment by kreezxil** [comment]
i'll use appimage for now.

**Comment by EnzoAlbornoz** [comment]
Go to `scripts/preinstall.js` then comment all the lines and try to build again.

**Comment by kreezxil** [comment]
oy vey, I'll try that.

**Comment by Eskaan** [comment]
> oy vey, I'll try that.

@kreezxil Tried? If this worked, please close this issue
