### ISSUE TITLE
1.1.1 requires latest libstdc++ (6.0.26) on Linux

### ISSUE THREAD

**Issue by desht** [gorilla-devs/GDLauncher#851]
**Describe the bug**
I went to start gdlauncher today on my Linux Mint 19.3 machine, and it crashed immediately:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/native/linux/nsfw.node: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.NR6fO1)
    at Object.eval (webpack-internal:///./public/native/linux/nsfw.node:1:233)
    at eval (webpack-internal:///./public/native/linux/nsfw.node:2:30)
    at Object../public/native/linux/nsfw.node (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:2954917)
    at g (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/native/nsfw.js:15:10)
    at Object../public/native/nsfw.js (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:2958169)
    at g (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/electron.js:49:14)
    at Object../public/electron.js (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:2909132)
    at g (/tmp/.mount_GDLaun8pOHDF/resources/app.asar/build/electron.js:1:124)
```
Since it had been working fine until now (and I presume it's the 1.1.1 release that's caused this), this is a regression, and a bit of a problem for all but the most recent Linux releases.  I don't know if there's a specific reason for this requirement or if there's an easy resolution not requiring hacky workarounds (see below).

**To Reproduce**
Simply try to run GDLauncher-linux-setup.AppImage (1.1.1 release) on a Linux Mint 19.3 PC, or any Linux system with a libstdc++.so older than 6.0.26, and it will crash with the above error.

**Expected behavior**
For a minor update to gdlauncher not to require a major OS upgrade? :)

**Possible solutions**
I was able to work around the problem by obtaining a copy of libstdc++.so.6.0.26 and symlinking it to the right place, but this isn't something I'd recommend for inexperienced Linux users, and does have the possibility of breaking other apps which are linked against an older libstdc++.

**Operating System:**
 - OS: Linux Mint
 - Version: 19.3

**Comment by jstansel** [comment]
Thanks for the work around. I have the experience to be able to do it but am certainly concerned about the possibility of breakage.

**Comment by nthdominion** [comment]
I also have issues on MX Linux.  Basically, we are between the Buster and Bullseye version of Linux.  The new build requires parts that will become native in Bullseye (latest GCC 9+).  While you can add this to systemd systems easier, adding this to vinit Linux can create real bastardizations of systems that cause a host of issues that most people cannot fix. Most of these will be fixed by the MX/ANTX team as the are going to a more normalized file structure (Ubuntu already uses this), sometime after Bullseye is released (latest info is Summer 2021).

**Comment by Jemsterr** [comment]
I was thinking of switching over from MultiMC (which I have used for years) but since my OS [Linux Mint 19.3] is not supported even though it is LTS, that is not an option.
