### ISSUE TITLE
Missing depandancy or wrong dependancy in .deb and also .appimage version.

### ISSUE THREAD

**Issue by jgilmore** [gorilla-devs/GDLauncher#890]
**Describe the bug**
When installing from .deb, there should NEVER be missing nor incompatible libraries when running the program. That's the point of the .deb format!

There is apparently NO format availble of this program that I can actually run?

**To Reproduce**
Install debian bionic.
Install GDlauncher using the .deb
 1. dpkg -i GDLauncher-linux-setup.deb
 2. apt install -f (If the dependency was correctly listed, this step would install it.)
 3. gdlauncher
 4. get library not found error

Tried the .appimage version, got the SAME ERROR

**Expected behavior**
If the packages listed dependencies are installed, the program should run.
If the .appimage version is used, it should run ANYWAY, even without dependencies deliberately installed.

**Possible solutions**
1. Add correct dependency to the .deb manifest so the correct library is installed.
2. Fix the library loading process can actually FIND the libs already installed on the system
   a.   REMOVE the funky LD path. This would require using the system libraries for ffmpeg, among other things. adding correct dependencies to the .deb manifest for these should be fairly trivial though.
   b.   prefix the LD path with your special location rather than replacing it.
3. Since BOTH the .deb and the .appimage give the same error, there may be something deeper going on, but I haven't the familiarity with the .appimage format to guess what it might be.

**Screenshots**
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /opt/GDLauncher/resources/app.asar/build/native/linux/nsfw.node: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.c8OTui)
    at Object.eval (webpack-internal:///./public/native/linux/nsfw.node:1:233)
    at eval (webpack-internal:///./public/native/linux/nsfw.node:2:30)
    at Object../public/native/linux/nsfw.node (/opt/GDLauncher/resources/app.asar/build/electron.js:1:2954917)
    at g (/opt/GDLauncher/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/native/nsfw.js:15:10)
    at Object../public/native/nsfw.js (/opt/GDLauncher/resources/app.asar/build/electron.js:1:2958169)
    at g (/opt/GDLauncher/resources/app.asar/build/electron.js:1:124)
    at eval (webpack-internal:///./public/electron.js:49:14)
    at Object../public/electron.js (/opt/GDLauncher/resources/app.asar/build/electron.js:1:2909132)
    at g (/opt/GDLauncher/resources/app.asar/build/electron.js:1:124)

**Operating System:**
ubuntu xenial

**Additional context**
I'm only (attempting to) install this because curseforge doesn't run on linux, requires .net 4.5 for windows, and is closed source so I can't fix it. I'm hoping to install a modpack from curseforge, which consists of a manifest file which specifies minecraft and forge versions and a big list of (presumably .jar) files to download, and a few configuration files.

Been working on getting it working for about five hours without luck. Admittedly, most of that was fiddling with wine & trying to get the curseforge launcher to work, but It really shouldn't be so difficult. If you can suggest a launcher which will work (if yours won't) I'd appriciate it.

**Comment by pniederlag** [comment]
it is a lot of work to maintain a .deb package over time and for all different versions of ubuntu. as it seems recent *.deb packages of gdlauncher are not compatible with older releases (beaver, xenial, ...). as libstdc++.so.6 is a very core component of debian/ubuntu you probably don't want to update it either.

**Comment by watermark** [comment]
Just wanted to double highlight that it's also happening in the AppImage. Also happening on Linux Mint 19.3 (which has an EOL of 3/2023)

**Comment by huantianad** [comment]
Agh dependency hell is the worst, I think you would need to update gcc which should update your libstdc++, but not sure the best way to do that on a static release distro...

Also will note that we don't make the .deb and .appimages ourselves, we have something ~~that I can't remember the name of~~ to make them.
