### ISSUE TITLE
Fabric won't launch w java 16

### ISSUE THREAD

**Issue by T1MOXA** [gorilla-devs/GDLauncher#960]
**Describe the bug**
Game not launching with Fabric

**To Reproduce**
1. Install Fabric 1.17
2. Launch
3. See error

**Operating System:**
 - OS: Windows 
 - Version: 10 21H1 
 - Build: 19043.1055

**Additional context**
```
[01:07:36] [main/INFO]: Loading for game Minecraft 1.17
actions.js:2695 [01:07:36] [main/INFO]: [FabricLoader] Loading 3 mods:
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17
actions.js:2695 [01:07:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/_gdl/datastore/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
01:07:36.653 › Detected 15 events from listener
actions.js:2695 [01:07:37] [main/WARN]: Failed to add PDH Counter: \���� ��������(_Total)\% Usage, Error code: 0xC0000BB8
actions.js:2695 [01:07:37] [main/WARN]: Failed to add counter for PDH object: ���� ��������
actions.js:2695 [01:07:37] [main/WARN]: Disabling further attempts to query Paging File.
actions.js:2695 [01:07:42] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
actions.js:2695 [01:07:42] [Render thread/INFO]: Setting user: ********
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
actions.js:2702 ps stderr: Exception in thread "Render thread" 
(anonymous) @ actions.js:2702
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[01:07:43] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	... 2 more
[01:07:43] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.platform.GLX.getOpenGLVersionString(GLX.java:35)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.getApiDescription(RenderSystem.java:770)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_6396.method_37123(class_6396.java:65)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_37274(class_310.java:2418)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_22681(class_310.java:2412)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:187)
actions.js:2695 [01:07:43] [Render thread/INFO]: [STDERR]: 	... 7 more
```

**Comment by Patate324** [comment]
I have a similar problem. In the command prompt, when i type: `java -version` it returns that am i running java 8, which is what minecraft used to use prior to java 16 (updated in minecraft java edition 1.17). I'm not sure why minecraft is able to run, because java edition now requires 1.17 to work, and works, however, GDLauncher doesn't want to work...
@T1MOXA did you solve this?

**Comment by T1MOXA** [comment]
> java -version

I have 
```
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by bread-tab** [comment]
Is there any way to solve this without externally installing Java?

Personally I have Java 16 installed, so I figure I could fix this by manually setting the path to it. But I'm troubleshooting on behalf of someone else so if it's possible to fix this without having them download a third party Java installer, I'd like to know.

**Comment by urmet** [comment]
currently there's no way to run 1.17 instances without you installing java 16 yourself.
automatic java 16 installation support is planned. I think one of the devs mentioned planning on doing it next week

**Comment by T1MOXA** [comment]
It didn't want to work even with the installed java 16, that's the problem...

**Comment by Patate324** [comment]
> I have a similar problem. In the command prompt, when i type: `java -version` it returns that am i running java 8, which is what minecraft used to use prior to java 16 (updated in minecraft java edition 1.17). I'm not sure why minecraft is able to run, because java edition now requires 1.17 to work, and works, however, GDLauncher doesn't want to work...
> @T1MOXA did you solve this?

I don’t get why I can play minecraft with the minecraft launcher but not play the last version on GDLauncher..?

**Comment by Cinnamon-Addict** [comment]
The same thing occurs with me, though i don't quite have enough knowledge to properly troubleshoot
